include:
  - local: .gitlab/ci/workflows/matrix_build_docker.yml
  - local: .gitlab/ci/workflows/matrix_build_helm.yml
  - local: .gitlab/ci/workflows/matrix_build_npm.yml

# DOCKER ===============================================================================================================
docker:
  extends:
    - .matrix_build_docker
  stage: build
  trigger:
    include:
      - local: '.gitlab/ci/pipelines/build/docker.yml'
    strategy: depend

# HELM =================================================================================================================
helm:
  extends:
    - .matrix_build_helm
  stage: build
  trigger:
    include:
      - component: $CI_SERVER_FQDN/shortlink-org/gitlab-templates/helm_publish@main
    strategy: depend
#  rules:
#    - if: $CI_COMMIT_TAG
#      when: on_success

# NPM Publish ==========================================================================================================
npm:
  extends:
    - .matrix_build_npm
  stage: build
  trigger:
    include:
      - component: $CI_SERVER_FQDN/shortlink-org/gitlab-templates/npm_publish@main
    strategy: depend
#  rules:
#    - if: $CI_COMMIT_TAG
#      when: on_success
