include:
  - local: .gitlab/ci/workflows/matrix_build_ui.yml

# DOCKER ===============================================================================================================
build:
  extends:
    - .matrix_build_ui
  stage: build
  trigger:
    include:
      - local: '.gitlab/ci/pipelines/build/docker_ui.yml'
    strategy: depend

# HELM =================================================================================================================
helm-chart:
  extends:
    - .matrix_build_helm
  stage: build
  trigger:
    include:
      - component: $CI_SERVER_FQDN/shortlink-org/gitlab-templates/helm_publish@main
    strategy: depend
#  rules:
#    - if: $CI_COMMIT_TAG
#      when: on_success

# NPM Publish ==========================================================================================================
npm-publish:
  extends:
    - .matrix_build_npm
  stage: build
  trigger:
    include:
      - component: $CI_SERVER_FQDN/shortlink-org/gitlab-templates/npm_publish@main
    strategy: depend
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
